# Generated by Django 3.2.1 on 2021-05-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='remind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_name', models.CharField(max_length=100, unique=True)),
                ('reminder_ctime', models.CharField(max_length=100)),
                ('reminder_detail', models.CharField(max_length=100)),
            ],
        ),
    ]
