# Generated by Django 3.2.4 on 2021-06-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remind',
            name='reminder_detail',
            field=models.CharField(max_length=200),
        ),
    ]
