# Generated by Django 3.2.1 on 2021-05-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('loss_url', models.CharField(max_length=100)),
                ('bili_url', models.CharField(max_length=100)),
                ('output_url', models.CharField(max_length=100)),
                ('project_acc', models.CharField(max_length=100)),
                ('project_recall', models.CharField(max_length=100)),
                ('project_prec', models.CharField(max_length=100)),
                ('project_auc', models.CharField(max_length=100)),
                ('project_time', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
    ]
