# Generated by Django 3.2 on 2021-04-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=100, unique=True)),
                ('dataset_url', models.CharField(max_length=100)),
                ('dataset_ctime', models.CharField(max_length=100)),
            ],
        ),
    ]
