# Generated by Django 3.2 on 2021-04-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('user_psd', models.CharField(max_length=100)),
                ('user_gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('user_tel', models.CharField(max_length=11)),
                ('user_status', models.IntegerField(choices=[(1, '正常'), (2, '封禁')], default=1)),
            ],
        ),
    ]
