# Generated by Django 3.2.1 on 2021-05-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_gender',
            field=models.CharField(default='男', max_length=32),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_status',
            field=models.IntegerField(default=1),
        ),
    ]
